### ISSUE TITLE
nif:topic assertions contains illegal punning

### ISSUE THREAD

**Issue by neradis** [NLP2RDF/ontologies#10]
This property is structurally violating OWL2 DL constraints: 

    nif:topic 
	    a owl:DatatypeProperty ;
    	owl:versionInfo "0.0.1" ; 
	    rdfs:label "topic" ;
	    rdfs:comment """The topic of a string
        Changelog:
        * 0.0.1 initial commit of property"""@en ;
	    rdfs:domain nif:String ;
        rdfs:range nif:Annotation .

@der-bruemmer Sebastian told me you added this property a bit 'quick-and-dirty' for GERBIL. How is it actually used there? (ObjectProperty pointing to nif:Annotation vs. DatatypeProperty with some string description)
@der-bruemmer Can you maybe also suggest a more fleshed-out description with better guidance when and how usage of this property is appropriate?

**Comment by der-bruemmer** [comment]
I'm not sure how it is actually used there, as the resultung annotated text is not exposed by GERBIL to my knowledge. The point of this property was to annotate a complete text with topical tags or entity classes, as opposed to a single entity, corresponding to the Rc2W task in GERBIL/BAT (see http://static.googleusercontent.com/media/research.google.com/de//pubs/archive/40749.pdf Table1). I'll ask the Gerbillians for more information.

It should be an ObjectProperty and I have no idea why I have added it as DatatypeProperty.

**Comment by VladimirAlexiev** [comment]
* If it's a property of the complete text, why not define the domain as `nif:Context`?
* For "topical tag", why not use `dct:subject` but invent a new property?
* For "entity class" why not use `its:taClassRef` but invent a new property?

**Comment by kurzum** [comment]
@der-bruemmer any updates?

**Comment by neradis** [comment]
> It should be an ObjectProperty and I have no idea why I have added it as DatatypeProperty.
I will change the property kind accordingly, which resolves the concrete issue described here.
We should still get input from the Gerbil users on why they wanted that property and how they use it to evaluate whether its range restriction does make sense, though.

**Comment by neradis** [comment]
Just saw that this happended already.
