### ISSUE TITLE
location of NIF3.0 and issue tracker

### ISSUE THREAD

**Issue by VladimirAlexiev** [NLP2RDF/ontologies#12]
1. Dmitris Kontokostas told me NIF 3.0 is coming out end of this month. Where can I take a look at a draft, and change log?
2. What's the preferred tracker? I see issues tracked here, but some months ago I posted a couple at https://github.com/NLP2RDF/specification/issues
3. Is it correct to make a reference to a linguistic resource, eg `itsrdf:taIdentRef bn:123456`. I though that taIdentRef is for named entities. I like such usage, but it should be clarified with an example.

Cheers!

**Comment by VladimirAlexiev** [comment]
- source: https://github.com/NLP2RDF/documentation/tree/2.1-RC/docs (last edit mid-Jan 2016)
- published: http://nif.readthedocs.org/en/2.1-rc/

**Comment by kurzum** [comment]
we are doing the ontology + documentation for NIF 2.1. Having an extra spec was a bit overkill. 
When @neradis is finished with the ontology other people from my team will take over with validator/json-context/updating implementation. 

After the Nif 2.1 Ontology release, discussion is moved here to prepare  proper W3C standardisation:
https://www.w3.org/community/ld4lt/

**Comment by kurzum** [comment]
Can this issue be closed?
