### ISSUE TITLE
annotations over strings

### ISSUE THREAD

**Issue by m1ci** [NLP2RDF/ontologies#13]
the idea is to enable annotation over strings. So that we could track provenance at annotation level - if needed. Currently, it is proposed to use `nif:AnnotationGroup` for this purpose.

**Comment by VladimirAlexiev** [comment]
@m1ci I don't understand, can you elaborate with an example?

**Comment by kurzum** [comment]
nif:AnnotationUnit https://github.com/NLP2RDF/ontologies/blob/nif2.1/nif-annotation/nif-annotation.ttl#L104 is supposed to replace nif Stanbol or better said move nif stanbol into core. 

Can this issue be closed?

**Comment by VladimirAlexiev** [comment]
If the issue is "introduce AnnotationUnit", close it. 
Please update the link above, it's currently broken.

**Comment by m1ci** [comment]
here it is
https://github.com/NLP2RDF/ontologies/blob/nif2.1/nif-core/nif-core.ttl#L895-L910
